### ISSUE TITLE
how to get train qrels dataset?

### ISSUE THREAD

**Issue by gm0616** [microsoft/MSMARCO-Document-Ranking#5]
Hey,  
I am confused about the meaning of "offset_trec" and "offset_tsv" in corpus _msmarco-docs-lookup.tsv_ , how to use this corpus to get a train dataset having format like "qid \t docid \t label"?

**Comment by bmitra-msft** [comment]
The training labels are available at: https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-doctrain-qrels.tsv.gz

They should have been listed under the data table but looks like they were missing. Sorry about that. I fixed it now.
