### ISSUE TITLE
Understanding of dataset structure

### ISSUE THREAD

**Issue by tommykoctur** [microsoft/MSMARCO-Document-Ranking#7]
Hello,
I had hard time to understand dataset structure and I was not able to find it anywhere.

I guess that:

- fulldocs.tsv are urls and documents and there are 3213835 lines (so each line is one document)
- docleaderboard-queries.tsv are ids and queries. 
- docleaderboard-top100.tsv are query to document relevancy dataset.
Structure: 
```
355339 Q0 D2612180 1 -5.21639 IndriQueryLikelihood

355339 Q0 D2906504 2 -5.22419 IndriQueryLikelihood

355339 Q0 D2076296 3 -5.39244 IndriQueryLikelihood

355339 Q0 D894964 4 -5.46692 IndriQueryLikelihood

355339 Q0 D260320 5 -5.47119 IndriQueryLikelihood
```

I assume first column is question ID, the second I don't know, the third possibly document id and next row is relevancy from 1-10, rest I don't care.
If DXXXXXX is document ID and as long as fulldocs.tsv has no ID in row, then I assume it is row number.
But if this is true, maximum DXXXXX number from docleaderboard-top100.tsv is D3563531 which is more than lines in fulldocs.tsv.

I am lost. Can you please help me. Is it possible that fulldocs.tsv is missing some docs ?

Thank you

**Comment by bhaskar-mitra** [comment]
Hello!

All the relevant datasets for the ranking leaderboard and corresponding documentations are available here: https://microsoft.github.io/msmarco/Datasets.

The corpus (https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-docs.tsv.gz) does contain document IDs that are used in the QRELs files (e.g., https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-doctrain-qrels.tsv.gz, https://msmarco.blob.core.windows.net/msmarcoranking/msmarco-docdev-qrels.tsv.gz).

The columns in the QRELs files are as follows: QueryID, IgnoreThisColumn, DocID, Rank, Score, RetrievalModel.

Please let us know if you have any other questions.

Best regards,
Bhaskar
